import { ValidationRun, Project } from "@/lib/types/schema";

export function generateMarkdownReport(project: Project, run: ValidationRun): string {
  const dateStr = new Date(run.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return `# PRODEXA — Launch Readiness Report

**Project**: ${project.name}
**Website**: ${project.websiteUrl}
**GitHub**: ${project.githubRepoUrl || "N/A"}
**Validated Date**: ${dateStr}
**Overall Launch Readiness Score**: ${run.overallScore !== null ? `${run.overallScore}%` : "N/A"}

---

## 1. Category Breakdown

- **Product Understanding**: ${run.moduleScores.productUnderstanding !== null ? `${run.moduleScores.productUnderstanding}%` : "Unable to analyze"}
- **Engineering Analysis**: ${run.moduleScores.engineering !== null ? `${run.moduleScores.engineering}%` : "Unable to analyze"}
- **UX Validation**: ${run.moduleScores.ux !== null ? `${run.moduleScores.ux}%` : "Unable to analyze"}
- **Performance Audit**: ${run.moduleScores.performance !== null ? `${run.moduleScores.performance}%` : "Unable to analyze"}
- **Accessibility Check**: ${run.moduleScores.accessibility !== null ? `${run.moduleScores.accessibility}%` : "Unable to analyze"}
- **Business Review**: ${run.moduleScores.business !== null ? `${run.moduleScores.business}%` : "Unable to analyze"}

---

## 2. Identified Issues & Copy-Fix Action Items

${run.issues
  .map(
    (issue, i) => `### ${i + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
**Category**: ${issue.category}
**Description**: ${issue.description}

**Deterministic Copy-Fix**:
\`\`\`
${issue.fixText}
\`\`\`
`
  )
  .join("\n")}

---

## 3. Prioritized Launch Roadmap

${run.roadmap
  .map(
    (item, i) =>
      `${i + 1}. **${item.title}** (${item.priority.toUpperCase()}) — Estimated Effort: ${item.estimatedEffort}`
  )
  .join("\n")}

---
*Report generated by Prodexa Pre-Launch Readiness Platform*
`;
}

export function downloadFile(filename: string, content: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
