import { ValidationRun, Project } from "@/lib/types/schema";
import { Blueprint } from "@/lib/types/blueprint";

export function generateMarkdownReport(project: Project, run: ValidationRun): string {
  const dateStr = new Date(run.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return `# PRODEXA — Launch Readiness Report

**Project**: ${project.name}
**Website**: ${project.websiteUrl}
**GitHub**: ${project.githubRepoUrl || "N/A"}
**Validated Date**: ${dateStr}
**Overall Launch Readiness Score**: ${run.overallScore !== null ? `${run.overallScore}%` : "N/A"}

---

## 1. Category Breakdown

- **Product Understanding**: ${run.moduleScores.productUnderstanding !== null ? `${run.moduleScores.productUnderstanding}%` : "Unable to analyze"}
- **Engineering Analysis**: ${run.moduleScores.engineering !== null ? `${run.moduleScores.engineering}%` : "Unable to analyze"}
- **UX Validation**: ${run.moduleScores.ux !== null ? `${run.moduleScores.ux}%` : "Unable to analyze"}
- **Performance Audit**: ${run.moduleScores.performance !== null ? `${run.moduleScores.performance}%` : "Unable to analyze"}
- **Accessibility Check**: ${run.moduleScores.accessibility !== null ? `${run.moduleScores.accessibility}%` : "Unable to analyze"}
- **Business Review**: ${run.moduleScores.business !== null ? `${run.moduleScores.business}%` : "Unable to analyze"}

---

## 2. Identified Issues & Copy-Fix Action Items

${run.issues
  .map(
    (issue, i) => `### ${i + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
**Category**: ${issue.category}
**Description**: ${issue.description}

**Deterministic Copy-Fix**:
\`\`\`
${issue.fixText}
\`\`\`
`
  )
  .join("\n")}

---

## 3. Prioritized Launch Roadmap

${run.roadmap
  .map(
    (item, i) =>
      `${i + 1}. **${item.title}** (${item.priority.toUpperCase()}) — Estimated Effort: ${item.estimatedEffort}`
  )
  .join("\n")}

---
*Report generated by Prodexa Pre-Launch Readiness Platform*
`;
}

export function generateStarterKitBundle(blueprint: Blueprint): string {
  const dateStr = new Date(blueprint.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const foundation = blueprint.sections.find((s) => s.category === "foundation")?.content || {};
  const tech = blueprint.sections.find((s) => s.category === "tech")?.content || {};
  const db = blueprint.sections.find((s) => s.category === "database")?.content || {};

  return `# ${blueprint.name.toUpperCase()} — ONE-CLICK PROJECT STARTER KIT
Generated on ${dateStr} by Prodexa (The AI Product Operating System)

================================================================================
FILE 1: README.md
================================================================================
# ${blueprint.name}

> ${blueprint.idea}

## Overview
${foundation.problemStatement || blueprint.problem}

## Core Solution
${foundation.solutionStatement || "Autonomous pre-launch software solution."}

## Target Audience
${foundation.targetICP || blueprint.targetUsers}

## Quick Start
\`\`\`bash
npm install
npm run dev
\`\`\`

================================================================================
FILE 2: PRD.md (Product Requirements Document)
================================================================================
# ${blueprint.name} — Product Requirements Document

## Problem Statement
${blueprint.problem}

## Solution & Value Proposition
${blueprint.idea}

## Quality Score Rating
- **Overall Score**: ${blueprint.qualityScore.overall}/100
- **Rationale**: ${blueprint.qualityScore.rationale}

================================================================================
FILE 3: TRD.md (Technical Requirements Document)
================================================================================
# ${blueprint.name} — Technical Requirements Document

## Tech Stack
- **Frontend**: ${tech.techStack?.frontend || "Next.js 14, Tailwind CSS"}
- **Backend**: ${tech.techStack?.backend || "Next.js API Server Routes"}
- **Database**: ${tech.techStack?.database || "Firebase Firestore"}
- **AI Engine**: ${tech.techStack?.ai || "OpenAI GPT-4o-mini"}

## System Architecture Diagram (Mermaid)
\`\`\`mermaid
${blueprint.mermaidDiagram}
\`\`\`

================================================================================
FILE 4: schema.json (Database Schema Specification)
================================================================================
${JSON.stringify(db.collections || [], null, 2)}

================================================================================
FILE 5: api-spec.json (REST Endpoints Specification)
================================================================================
${JSON.stringify(db.endpoints || [], null, 2)}

================================================================================
FILE 6: .env.example
================================================================================
NEXT_PUBLIC_APP_NAME="${blueprint.name}"
DATABASE_URL=your_database_connection_string
OPENAI_API_KEY=your_openai_api_key
`;
}

export function downloadFile(filename: string, content: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
