import { ValidationRun, Project } from "@/lib/types/schema";
import { Blueprint } from "@/lib/types/blueprint";

export function generateMarkdownReport(project: Project, run: ValidationRun): string {
  const dateStr = new Date(run.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return `# PRODEXA — Launch Readiness Report

**Project**: ${project.name}
**Website**: ${project.websiteUrl}
**GitHub**: ${project.githubRepoUrl || "N/A"}
**Validated Date**: ${dateStr}
**Overall Launch Readiness Score**: ${run.overallScore !== null ? `${run.overallScore}%` : "N/A"}

---

## 1. Category Breakdown

- **Product Understanding**: ${run.moduleScores.productUnderstanding !== null ? `${run.moduleScores.productUnderstanding}%` : "Unable to analyze"}
- **Engineering Analysis**: ${run.moduleScores.engineering !== null ? `${run.moduleScores.engineering}%` : "Unable to analyze"}
- **UX Validation**: ${run.moduleScores.ux !== null ? `${run.moduleScores.ux}%` : "Unable to analyze"}
- **Web Performance Snapshot**: ${run.moduleScores.performance !== null ? `${run.moduleScores.performance}%` : "Unable to analyze"}
- **Accessibility Check**: ${run.moduleScores.accessibility !== null ? `${run.moduleScores.accessibility}%` : "Unable to analyze"}
- **Business Review**: ${run.moduleScores.business !== null ? `${run.moduleScores.business}%` : "Unable to analyze"}

---

## 2. Identified Issues & Copy-Fix Action Items

${run.issues
  .map(
    (issue, i) => `### ${i + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
**Category**: ${issue.category}
**Description**: ${issue.description}

**Deterministic Copy-Fix**:
\`\`\`
${issue.fixText}
\`\`\`
`
  )
  .join("\n")}

---

## 3. Prioritized Launch Roadmap

${run.roadmap
  .map(
    (item, i) =>
      `${i + 1}. **${item.title}** (${item.priority.toUpperCase()}) — Estimated Effort: ${item.estimatedEffort}`
  )
  .join("\n")}

---
*Report generated by Prodexa AI Product Operating System*
`;
}

export function generateStarterKitBundle(blueprint: Blueprint): string {
  const dateStr = new Date(blueprint.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const foundation = blueprint.sections.find((s) => s.category === "foundation")?.content || {};
  const tech = blueprint.sections.find((s) => s.category === "tech")?.content || {};
  const db = blueprint.sections.find((s) => s.category === "database")?.content || {};
  const features = blueprint.sections.find((s) => s.category === "features")?.content || {};

  return `# ${blueprint.name.toUpperCase()} — ONE-CLICK PROJECT STARTER KIT BUNDLE
Generated on ${dateStr} by Prodexa (The AI Product Operating System)

================================================================================
FILE 1: README.md
================================================================================
# ${blueprint.name}

> ${blueprint.idea}

## Problem Statement
${foundation.problemStatement || blueprint.problem}

## Core Solution
${foundation.solutionStatement || "Autonomous pre-launch software solution."}

## Target Ideal Customer Profile (ICP)
${foundation.targetICP || blueprint.targetUsers || "Software teams and founders"}

## Quick Start
\`\`\`bash
npm install
npm run dev
\`\`\`

================================================================================
FILE 2: PRD.md (Product Requirements Document)
================================================================================
# PRD: ${blueprint.name}

## 1. Product Vision
${blueprint.idea}

## 2. Core MVP Features
${(features.mvpFeatures || ["Core User Dashboard", "AI Engine Endpoint"]).map((f: string) => `- ${f}`).join("\n")}

## 3. Future Roadmap
${(features.futureFeatures || ["Slack Integration", "Webhook Alerts"]).map((f: string) => `- ${f}`).join("\n")}

## 4. Monetization Strategy
${features.monetization || "Freemium SaaS tier."}

================================================================================
FILE 3: TRD.md (Technical Requirements Document)
================================================================================
# TRD: ${blueprint.name}

## 1. Technology Stack
- **Frontend**: ${tech.techStack?.frontend || "Next.js 14, React, Tailwind CSS"}
- **Backend**: ${tech.techStack?.backend || "Next.js API Server Routes"}
- **Database**: ${tech.techStack?.database || "Firebase Firestore"}
- **AI Engine**: ${tech.techStack?.ai || "Gemini / OpenAI Engine"}

## 2. System Architecture Diagram
\`\`\`mermaid
${blueprint.mermaidDiagram}
\`\`\`

================================================================================
FILE 4: LICENSE (MIT License)
================================================================================
MIT License

Copyright (c) 2026 ${blueprint.name} Team

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction...

================================================================================
FILE 5: .env.example
================================================================================
# Environment Configuration
NEXT_PUBLIC_APP_NAME="${blueprint.name}"
NEXT_PUBLIC_FIREBASE_API_KEY="your-firebase-api-key"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="your-project-id"
GEMINI_API_KEY="your-gemini-api-key"
OPENAI_API_KEY="your-openai-api-key"

================================================================================
FILE 6: api-spec.json
================================================================================
${JSON.stringify(db.endpoints || [
  { method: "POST", path: "/api/generate", desc: "Main AI processing endpoint" }
], null, 2)}

================================================================================
FILE 7: schema.json
================================================================================
${JSON.stringify(db.collections || [
  { name: "users", fields: "uid, email, displayName" },
  { name: "projects", fields: "id, name, contextPackage" }
], null, 2)}

================================================================================
FILE 8: development-tasks.md
================================================================================
1. [HIGH] Initialize Next.js 14 repository with Tailwind CSS and Inter font
2. [HIGH] Configure Firebase Admin SDK & Firestore database rules
3. [MEDIUM] Build core user dashboard and AI processing API routes
4. [MEDIUM] Execute pre-launch audit validation and export starter kit
`;
}

export function downloadFile(filename: string, text: string, type = "text/plain"): void {
  const element = document.createElement("a");
  const file = new Blob([text], { type });
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}
